// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxCGlx_oavixosYWctL43Rj2NAM0XUWY4',
    appId: '1:779335770828:web:d39a3011c41c849f821869',
    messagingSenderId: '779335770828',
    projectId: 'sih23-bf8c1',
    authDomain: 'sih23-bf8c1.firebaseapp.com',
    storageBucket: 'sih23-bf8c1.appspot.com',
    measurementId: 'G-51R92N8E8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEAa6f-sZc3RhHjLIjRHTNMRF8VCs-gjU',
    appId: '1:779335770828:android:240f51c14300473e821869',
    messagingSenderId: '779335770828',
    projectId: 'sih23-bf8c1',
    storageBucket: 'sih23-bf8c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ermkbthb3WgFdRCqobrM2e5M3WSRYmk',
    appId: '1:779335770828:ios:068ad2a2179bff4d821869',
    messagingSenderId: '779335770828',
    projectId: 'sih23-bf8c1',
    storageBucket: 'sih23-bf8c1.appspot.com',
    iosClientId: '779335770828-v4utp9bv19dsn4uv316ev3iigk6q0vgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sihChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ermkbthb3WgFdRCqobrM2e5M3WSRYmk',
    appId: '1:779335770828:ios:65278fbd79f244df821869',
    messagingSenderId: '779335770828',
    projectId: 'sih23-bf8c1',
    storageBucket: 'sih23-bf8c1.appspot.com',
    iosClientId: '779335770828-fh16njst5nt3qfp5kbeniua829mk0tkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sihChatbot.RunnerTests',
  );
}
